=== Stucom-Pelai/M07_UF3_Eloquent-Hospital/app/Http/Controllers/wsdl/Hospital.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema targetNamespace="http://hospital.hms.com/service"  
	xmlns:xs="http://www.w3.org/2001/XMLSchema" 
	xmlns="http://hospital.hms.com/service" 
	elementFormDefault="qualified">
	<xs:import namespace="http://www.w3.org/XML/1998/namespace"/>
	<xs:complexType name="HospitalType">
		<xs:sequence>
			<xs:sequence>
				<xs:element ref="Infrastructure"/>
				<xs:element ref="Staff"/>
				<xs:element ref="Patients"/>
				<xs:element ref="History"/>
				<xs:element ref="Reception"/>
				<xs:element ref="Accounting"/>
			</xs:sequence>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="Hospital" type="HospitalType"/>
	<xs:complexType name="InfrastructureType">
		<xs:sequence>
			<xs:choice>
				<xs:element ref="Wings" maxOccurs="unbounded"/>
			</xs:choice>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="Infrastructure" type="InfrastructureType"/>
	<xs:complexType name="WingsType">
		<xs:sequence>
			<xs:choice>
				<xs:element ref="Wing" maxOccurs="unbounded"/>
			</xs:choice>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="Wings" type="WingsType"/>
	<xs:complexType name="WingType">
		<xs:sequence>
			<xs:sequence>
				<xs:element ref="Departments" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="Wards" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:sequence>
		<xs:attribute name="wingID" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:ID">
					<xs:pattern value="Wing[0-9]+"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:element name="Wing" type="WingType"/>
	<xs:complexType name="DepartmentsType">
		<xs:sequence>
			<xs:choice>
				<xs:element ref="Department" maxOccurs="unbounded"/>
			</xs:choice>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="Departments" type="DepartmentsType"/>
	<xs:complexType name="DepartmentType">
		<xs:sequence>
			<xs:sequence>
				<xs:element ref="DepartmentName"/>
				<xs:element ref="DepartmentPhone" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:sequence>
		<xs:attribute name="DeptartID" type="xs:ID" use="required"/>
		<xs:attribute name="useWard" type="xs:IDREF"/>
	</xs:complexType>
	<xs:element name="Department" type="DepartmentType"/>
	<xs:element name="DepartmentName" type="xs:string"/>
	<xs:element name="DepartmentPhone" type="xs:string"/>
	<xs:complexType name="WardsType">
		<xs:sequence>
			<xs:choice>
				<xs:element ref="Ward" maxOccurs="unbounded"/>
			</xs:choice>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="Wards" type="WardsType"/>
	<xs:complexType name="WardType">
		<xs:sequence>
			<xs:choice>
				<xs:element ref="Rooms" maxOccurs="unbounded"/>
			</xs:choice>
		</xs:sequence>
		<xs:attribute name="WardID" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:ID">
					<xs:pattern value="Wing[0-9]+Ward[0-9]+"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:element name="Ward" type="WardType"/>
	<xs:complexType name="RoomsType">
		<xs:sequence>
			<xs:choice>
				<xs:element ref="Room" maxOccurs="unbounded"/>
			</xs:choice>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="Rooms" type="RoomsType"/>
	<xs:complexType name="RoomType">
		<xs:sequence>
			<xs:choice>
				<xs:element ref="Beds" maxOccurs="unbounded"/>
			</xs:choice>
		</xs:sequence>
		<xs:attribute name="RoomID" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:ID">
					<xs:pattern value="Wing[0-9]+Ward[0-9]+Room[0-9]+"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="RoomSize" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:NMTOKEN">
					<xs:enumeration value="2"/>
					<xs:enumeration value="3"/>
					<xs:enumeration value="4"/>
					<xs:enumeration value="5"/>
					<xs:enumeration value="6"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:element name="Room" type="RoomType"/>
	<xs:complexType name="BedsType">
		<xs:sequence>
			<xs:choice>
				<xs:element ref="Bed" maxOccurs="unbounded"/>
			</xs:choice>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="Beds" type="BedsType"/>
	<xs:complexType name="BedType">
		<xs:attribute name="BedID" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:ID">
					<xs:pattern value="Wing[0-9]+Ward[0-9]+Room[0-9]+Bed[0-9]+"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="BedSize" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:NMTOKEN">
					<xs:enumeration value="1"/>
					<xs:enumeration value="2"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:element name="Bed" type="BedType"/>
	<xs:complexType name="StaffType">
		<xs:sequence maxOccurs="unbounded">
			<xs:element ref="Doctors"/>
			<xs:element ref="Nurses"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="Staff" type="StaffType"/>
	<xs:complexType name="DoctorsType">
		<xs:sequence>
			<xs:element ref="Doctor" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="Doctors" type="DoctorsType"/>
	<xs:complexType name="DoctorType">
		<xs:sequence>
			<xs:sequence>
				<xs:element ref="DoctorName"/>
				<xs:element ref="Speciality"/>
				<xs:element ref="Relantionship"/>
				<xs:element ref="DoctorContact"/>
			</xs:sequence>
		</xs:sequence>
		<xs:attribute name="DoctorID" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:ID">
					<xs:pattern value="Doctor[0-9]+"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="WorksIn" type="xs:IDREF" use="required"/>
		<xs:attribute name="HeadOfDept" type="xs:IDREF"/>
	</xs:complexType>
	<xs:element name="Doctor" type="DoctorType"/>
	<xs:element name="DoctorName" type="xs:string"/>
	<xs:element name="Speciality" type="xs:string"/>
	<xs:complexType name="RelantionshipT">
		<xs:attribute name="RelantionshipType" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:NMTOKEN">
					<xs:enumeration value="Trainee"/>
					<xs:enumeration value="Visiting"/>
					<xs:enumeration value="Permanent"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:element name="Relantionship" type="RelantionshipT"/>
	<xs:complexType name="DoctorContactType">
		<xs:sequence>
			<xs:sequence>
				<xs:element ref="DoctorAddress"/>
				<xs:element ref="DoctorPhone" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="DoctorContact" type="DoctorContactType"/>
	<xs:element name="DoctorAddress" type="xs:string"/>
	<xs:element name="DoctorPhone" type="xs:string"/>
	<xs:complexType name="NursesType">
		<xs:sequence>
			<xs:element ref="Nurse" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="Nurses" type="NursesType"/>
	<xs:complexType name="NurseType">
		<xs:sequence>
			<xs:sequence>
				<xs:element ref="NurseName"/>
				<xs:element ref="NurseContact"/>
			</xs:sequence>
		</xs:sequence>
		<xs:attribute name="NurseID" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:ID">
					<xs:pattern value="Nurse[0-9]+"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="WorksIn" type="xs:IDREF" use="required"/>
		<xs:attribute name="InspectWard" type="xs:IDREF"/>
	</xs:complexType>
	<xs:element name="Nurse" type="NurseType"/>
	<xs:element name="NurseName" type="xs:string"/>
	<xs:complexType name="NurseContactType">
		<xs:sequence>
			<xs:sequence>
				<xs:element name="NurseAddress" type="xs:string"/>
				<xs:element name="NursePhone" type="xs:string" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="NurseContact" type="NurseContactType"/>
	<xs:complexType name="PatientsType">
		<xs:sequence>
			<xs:element ref="Patient" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="Patients" type="PatientsType"/>
	<xs:complexType name="PatientType">
		<xs:sequence>
			<xs:sequence>
				<xs:element ref="PatientName"/>
				<xs:element ref="Sex"/>
				<xs:element ref="Weight"/>
				<xs:element ref="Age"/>
				<xs:element ref="AttendedDept" minOccurs="0"/>
				<xs:element ref="AttendedDoctor"/>
				<xs:element ref="BedTo"/>
				<xs:element ref="RecoveryPeriod"/>
				<xs:element ref="PatientContact"/>
			</xs:sequence>
		</xs:sequence>
		<xs:attribute name="PatientID" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:ID">
					<xs:pattern value="Patient[0-9]+"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="PatientType" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:NMTOKEN">
					<xs:enumeration value="OutPatient"/>
					<xs:enumeration value="InPatient"/>
					<xs:enumeration value="VisitPatient"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:element name="Patient" type="PatientType"/>
	<xs:element name="PatientName" type="xs:string"/>
	<xs:complexType name="SexType">
		<xs:attribute name="GenderGategory" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:NMTOKEN">
					<xs:enumeration value="Female"/>
					<xs:enumeration value="Male"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:element name="Sex" type="SexType"/>
	<xs:complexType name="WeightType">
		<xs:attribute name="PatientWeight" type="xs:string"/>
	</xs:complexType>
	<xs:element name="Weight" type="WeightType"/>
	<xs:complexType name="AgeType">
		<xs:attribute name="PatientAge" type="xs:int"/>
	</xs:complexType>
	<xs:element name="Age" type="AgeType"/>
	<xs:complexType name="AttendedDeptType">
		<xs:attribute name="AttendedIn" type="xs:IDREF"/>
	</xs:complexType>
	<xs:element name="AttendedDept" type="AttendedDeptType"/>
	<xs:complexType name="AttendedDoctorType">
		<xs:attribute name="AttendedBy" type="xs:IDREFS"/>
	</xs:complexType>
	<xs:element name="AttendedDoctor" type="AttendedDoctorType"/>
	<xs:complexType name="BedToType">
		<xs:attribute name="assignedBed" type="xs:IDREF"/>
	</xs:complexType>
	<xs:element name="BedTo" type="BedToType"/>
	<xs:complexType name="RecoveryPeriodType">
		<xs:attribute name="dateAdmitted" type="xs:date"/>
		<xs:attribute name="dateDischarged" type="xs:date"/>
	</xs:complexType>
	<xs:element name="RecoveryPeriod" type="RecoveryPeriodType"/>
	<xs:complexType name="PatientContactType">
		<xs:sequence>
			<xs:sequence>
				<xs:element ref="PatientAddress"/>
				<xs:element ref="PatientPhone" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="PatientContact" type="PatientContactType"/>
	<xs:element name="PatientAddress" type="xs:string"/>
	<xs:element name="PatientPhone" type="xs:string"/>
	<xs:complexType name="HistoryType">
		<xs:sequence>
			<xs:choice>
				<xs:element ref="Record" maxOccurs="unbounded"/>
			</xs:choice>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="History" type="HistoryType"/>
	<xs:complexType name="RecordType">
		<xs:sequence>
			<xs:sequence>
				<xs:element ref="AffiliatedPatient"/>
				<xs:element ref="PatientState"/>
				<xs:element ref="HistoryUpdate" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:sequence>
		<xs:attribute name="HistoryRecID" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:ID">
					<xs:pattern value="Record[0-9]+"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:element name="Record" type="RecordType"/>
	<xs:complexType name="AffiliatedPatientType">
		<xs:attribute name="AffiliatedPatientID" type="xs:IDREF" use="required"/>
	</xs:complexType>
	<xs:element name="AffiliatedPatient" type="AffiliatedPatientType"/>
	<xs:complexType name="PatientStateType">
		<xs:attribute name="Pstate" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:NMTOKEN">
					<xs:enumeration value="Sick"/>
					<xs:enumeration value="Diseased"/>
					<xs:enumeration value="Severe"/>
					<xs:enumeration value="Good"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:element name="PatientState" type="PatientStateType"/>
	<xs:complexType name="HistoryUpdateType">
		<xs:sequence>
			<xs:sequence>
				<xs:element ref="UpdateDate"/>
				<xs:element ref="UpdateTime"/>
				<xs:element ref="AffiliatedDoctor"/>
				<xs:element ref="AffiliatedDepart"/>
				<xs:element ref="MedicalCase"/>
				<xs:element ref="DoctorComments"/>
				<xs:element ref="Prescription"/>
			</xs:sequence>
		</xs:sequence>
		<xs:attribute name="HistoryUpdateID" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:ID">
					<xs:pattern value="HistoryUpdate[0-9]+"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:element name="HistoryUpdate" type="HistoryUpdateType"/>
	<xs:complexType name="UpdateDateType">
		<xs:attribute name="UptDate" type="xs:date" use="required"/>
	</xs:complexType>
	<xs:element name="UpdateDate" type="UpdateDateType"/>
	<xs:complexType name="UpdateTimeType">
		<xs:attribute name="UptTime" type="xs:time" use="required"/>
	</xs:complexType>
	<xs:element name="UpdateTime" type="UpdateTimeType"/>
	<xs:complexType name="AffiliatedDoctorType">
		<xs:attribute name="AffiliatedDoctorID" type="xs:IDREF" use="required"/>
	</xs:complexType>
	<xs:element name="AffiliatedDoctor" type="AffiliatedDoctorType"/>
	<xs:complexType name="AffiliatedDepartType">
		<xs:attribute name="AffiliatedDepartID" type="xs:IDREF" use="required"/>
	</xs:complexType>
	<xs:element name="AffiliatedDepart" type="AffiliatedDepartType"/>
	<xs:element name="MedicalCase" type="xs:string"/>
	<xs:element name="DoctorComments" type="xs:string"/>
	<xs:element name="PrescriptionComments" type="xs:string"/>
	<xs:complexType name="PrescriptionType">
		<xs:sequence>
			<xs:element ref="Pill" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="Prescription" type="PrescriptionType"/>
	<xs:complexType name="PillType">
		<xs:attribute name="PillName" type="xs:string" use="required"/>
		<xs:attribute name="Instructions" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:element name="Pill" type="PillType"/>
	<xs:complexType name="ReceptionType">
		<xs:sequence>
			<xs:choice>
				<xs:element ref="Appointment" maxOccurs="unbounded"/>
			</xs:choice>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="Reception" type="ReceptionType"/>
	<xs:complexType name="AppointmentType">
		<xs:sequence>
			<xs:sequence>
				<xs:element ref="AppointedDoctor"/>
				<xs:element ref="AppointedPatient"/>
				<xs:element ref="AppointedDate"/>
				<xs:element ref="AppointedTime"/>
				<xs:element ref="comments"/>
			</xs:sequence>
		</xs:sequence>
		<xs:attribute name="AppointmentID" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:ID">
					<xs:pattern value="Appointment[0-9]+"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:element name="Appointment" type="AppointmentType"/>
	<xs:complexType name="AppointedDoctorType">
		<xs:attribute name="AppointedDoctorID" type="xs:IDREF" use="required"/>
	</xs:complexType>
	<xs:element name="AppointedDoctor" type="AppointedDoctorType"/>
	<xs:complexType name="AppointedPatientType">
		<xs:attribute name="AppointedPatientID" type="xs:IDREF" use="required"/>
	</xs:complexType>
	<xs:element name="AppointedPatient" type="AppointedPatientType"/>
	<xs:complexType name="AppointedDateType">
		<xs:attribute name="Aptdate" type="xs:date" use="required"/>
	</xs:complexType>
	<xs:element name="AppointedDate" type="AppointedDateType"/>
	<xs:complexType name="AppointedTimeType">
		<xs:attribute name="AptTime" type="xs:time"/>
	</xs:complexType>
	<xs:element name="AppointedTime" type="AppointedTimeType"/>
	<xs:element name="comments" type="xs:string"/>
	<xs:complexType name="AccountingType">
		<xs:sequence>
			<xs:sequence>
				<xs:element ref="Expenditures"/>
				<xs:element ref="Incomes"/>
			</xs:sequence>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="Accounting" type="AccountingType"/>
	<xs:complexType name="ExpendituresType">
		<xs:sequence>
			<xs:sequence>
				<xs:element ref="Salaries"/>
				<xs:element ref="MiscellaneousOrders"/>
			</xs:sequence>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="Expenditures" type="ExpendituresType"/>
	<xs:complexType name="SalariesType">
		<xs:sequence>
			<xs:choice>
				<xs:element ref="Salary" maxOccurs="unbounded"/>
			</xs:choice>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="Salaries" type="SalariesType"/>
	<xs:complexType name="SalaryType">
		<xs:sequence>
			<xs:choice>
				<xs:element ref="Payment"/>
			</xs:choice>
		</xs:sequence>
		<xs:attribute name="SalaryID" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:ID">
					<xs:pattern value="Salary[0-9]+"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="staffID" type="xs:IDREF" use="required"/>
	</xs:complexType>
	<xs:element name="Salary" type="SalaryType"/>
	<xs:complexType name="PaymentType">
		<xs:attribute name="amount" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:NMTOKEN">
					<xs:enumeration value="1800"/>
					<xs:enumeration value="1500"/>
					<xs:enumeration value="1200"/>
					<xs:enumeration value="900"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:element name="Payment" type="PaymentType"/>
	<xs:complexType name="MiscellaneousOrdersType">
		<xs:sequence>
			<xs:choice>
				<xs:element ref="Order" maxOccurs="unbounded"/>
			</xs:choice>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="MiscellaneousOrders" type="MiscellaneousOrdersType"/>
	<xs:complexType name="OrderType">
		<xs:sequence>
			<xs:choice>
				<xs:element ref="Cost"/>
			</xs:choice>
		</xs:sequence>
		<xs:attribute name="OrderID" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:ID">
					<xs:pattern value="Order[0-9]+"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="ForDepartment" type="xs:IDREFS" use="required"/>
		<xs:attribute name="OrderDate" type="xs:date" use="required"/>
	</xs:complexType>
	<xs:element name="Order" type="OrderType"/>
	<xs:complexType name="CostType">
		<xs:attribute name="TotalCost" type="xs:double" use="required"/>
	</xs:complexType>
	<xs:element name="Cost" type="CostType"/>
	<xs:complexType name="IncomesType">
		<xs:sequence>
			<xs:choice>
				<xs:element ref="PatientBill" maxOccurs="unbounded"/>
			</xs:choice>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="Incomes" type="IncomesType"/>
	<xs:complexType name="PatientBillType">
		<xs:sequence>
			<xs:choice>
				<xs:element ref="BillCost"/>
			</xs:choice>
		</xs:sequence>
		<xs:attribute name="BillID" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:ID">
					<xs:pattern value="Bill[0-9]+"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="BilledPatient" type="xs:IDREF" use="required"/>
	</xs:complexType>
	<xs:element name="PatientBill" type="PatientBillType"/>
	<xs:complexType name="BillCostType">
		<xs:attribute name="amount" type="xs:double" use="required"/>
	</xs:complexType>
	<xs:element name="BillCost" type="BillCostType"/>
</xs:schema>

=== Stucom-Pelai/M07_UF3_Eloquent-Hospital/app/Http/Controllers/wsdl/Hospital.xml
<?xml version="1.0" encoding="UTF-8"?>
<Hospital xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Hospital.xsd">
	<Infrastructure>
		<Wings>
			<Wing wingID="Wing101">
				<Departments>
					<Department DeptartID="_Walk_in_Clinic">
						<DepartmentName>Walk In Clinic</DepartmentName>
						<DepartmentPhone>202-555-0154</DepartmentPhone>
					</Department>
					<Department DeptartID="_Nephrology" useWard="Wing101Ward101">
						<DepartmentName>Nephrology</DepartmentName>
						<DepartmentPhone>202-555-0199</DepartmentPhone>
					</Department>
					<Department DeptartID="_Microbiology">
						<DepartmentName>Microbiology</DepartmentName>
						<DepartmentPhone>202-555-0189</DepartmentPhone>
					</Department>
				</Departments>
				<Wards>
					<Ward WardID="Wing101Ward106">
						<Rooms>
							<Room RoomSize="2" RoomID="Wing101Ward106Room101">
								<Beds>
									<Bed BedSize="2" BedID="Wing101Ward106Room101Bed101"/>
									<Bed BedSize="2" BedID="Wing101Ward106Room101Bed102"/>
								</Beds>
							</Room>
						</Rooms>
					</Ward>
					<Ward WardID="Wing101Ward101">
						<Rooms>
							<Room RoomID="Wing101Ward101Room101" RoomSize="3">
								<Beds>
									<Bed BedID="Wing101Ward101Room101Bed101" BedSize="1"/>
									<Bed BedID="Wing101Ward101Room101Bed102" BedSize="2"/>
									<Bed BedID="Wing101Ward101Room101Bed103" BedSize="1"/>
								</Beds>
							</Room>
							<Room RoomID="Wing101Ward101Room102" RoomSize="3">
								<Beds>
									<Bed BedID="Wing101Ward101Room102Bed101" BedSize="1"/>
									<Bed BedID="Wing101Ward101Room102Bed102" BedSize="2"/>
									<Bed BedID="Wing101Ward101Room102Bed103" BedSize="2"/>
								</Beds>
							</Room>
							<Room RoomID="Wing101Ward101Room103" RoomSize="6">
								<Beds>
									<Bed BedID="Wing101Ward101Room103Bed101" BedSize="1"/>
									<Bed BedID="Wing101Ward101Room103Bed102" BedSize="2"/>
									<Bed BedID="Wing101Ward101Room103Bed103" BedSize="2"/>
									<Bed BedID="Wing101Ward101Room103Bed104" BedSize="1"/>
									<Bed BedID="Wing101Ward101Room103Bed105" BedSize="2"/>
									<Bed BedID="Wing101Ward101Room103Bed106" BedSize="2"/>
								</Beds>
							</Room>
						</Rooms>
					</Ward>
				</Wards>
			</Wing>
			<Wing wingID="Wing102">
				<Departments>
					<Department DeptartID="_Oncology" useWard="Wing102Ward102">
						<DepartmentName>Oncology</DepartmentName>
						<DepartmentPhone>202-555-0100</DepartmentPhone>
					</Department>
				</Departments>
				<Wards>
					<Ward WardID="Wing102Ward102">
						<Rooms>
							<Room RoomID="Wing102Ward102Room101" RoomSize="3">
								<Beds>
									<Bed BedSize="1" BedID="Wing102Ward102Room101Bed101"/>
									<Bed BedSize="1" BedID="Wing102Ward102Room101Bed102"/>
									<Bed BedSize="1" BedID="Wing102Ward102Room101Bed103"/>
								</Beds>
							</Room>
							<Room RoomID="Wing102Ward102Room102" RoomSize="2">
								<Beds>
									<Bed BedSize="1" BedID="Wing102Ward102Room102Bed101"/>
									<Bed BedSize="1" BedID="Wing102Ward102Room102Bed102"/>
								</Beds>
							</Room>
							<Room RoomID="Wing102Ward102Room103" RoomSize="5">
								<Beds>
									<Bed BedSize="2" BedID="Wing102Ward102Room103Bed101"/>
									<Bed BedSize="2" BedID="Wing102Ward102Room103Bed102"/>
									<Bed BedSize="2" BedID="Wing102Ward102Room103Bed103"/>
									<Bed BedSize="2" BedID="Wing102Ward102Room103Bed104"/>
									<Bed BedSize="1" BedID="Wing102Ward102Room103Bed105"/>
								</Beds>
							</Room>
						</Rooms>
					</Ward>
				</Wards>
			</Wing>
			<Wing wingID="Wing103">
				<Departments>
					<Department DeptartID="_Cardiology" useWard="Wing103Ward101">
						<DepartmentName>Cardiology</DepartmentName>
						<DepartmentPhone>202-555-0168</DepartmentPhone>
					</Department>
					<Department DeptartID="_General_Surgery" useWard="Wing103Ward102">
						<DepartmentName>General Surgery</DepartmentName>
						<DepartmentPhone>202-555-0101</DepartmentPhone>
					</Department>
				</Departments>
				<Wards>
					<Ward WardID="Wing103Ward101">
						<Rooms>
							<Room RoomID="Wing103Ward101Room101" RoomSize="2">
								<Beds>
									<Bed BedSize="2" BedID="Wing103Ward101Room101Bed101"/>
									<Bed BedSize="2" BedID="Wing103Ward101Room101Bed102"/>
								</Beds>
							</Room>
						</Rooms>
					</Ward>
					<Ward WardID="Wing103Ward102">
						<Rooms>
							<Room RoomID="Wing103Ward102Room101" RoomSize="4">
								<Beds>
									<Bed BedSize="1" BedID="Wing103Ward102Room101Bed101"/>
									<Bed BedSize="2" BedID="Wing103Ward102Room101Bed102"/>
									<Bed BedSize="1" BedID="Wing103Ward102Room101Bed103"/>
									<Bed BedSize="1" BedID="Wing103Ward102Room101Bed104"/>
								</Beds>
							</Room>
							<Room RoomID="Wing103Ward102Room102" RoomSize="3">
								<Beds>
									<Bed BedSize="1" BedID="Wing103Ward102Room102Bed101"/>
									<Bed BedSize="2" BedID="Wing103Ward102Room102Bed102"/>
									<Bed BedSize="2" BedID="Wing103Ward102Room102Bed103"/>
								</Beds>
							</Room>
						</Rooms>
					</Ward>
				</Wards>
			</Wing>
		</Wings>
	</Infrastructure>
	<Staff>
		<Doctors>
			<Doctor DoctorID="Doctor101" WorksIn="_Nephrology">
				<DoctorName>Priscilla Arnold</DoctorName>
				<Speciality>Nephrologist</Speciality>
				<Relantionship RelantionshipType="Trainee"/>
				<DoctorContact>
					<DoctorAddress>326 Willow Street Rowlett, TX 75088</DoctorAddress>
					<DoctorPhone>202-555-0168</DoctorPhone>
				</DoctorContact>
			</Doctor>
			<Doctor DoctorID="Doctor102" WorksIn="_Nephrology">
				<DoctorName>Jenna	Floyd</DoctorName>
				<Speciality>Nephrologist</Speciality>
				<Relantionship RelantionshipType="Permanent"/>
				<DoctorContact>
					<DoctorAddress>68 Spring Street Marysville, OH 43040</DoctorAddress>
					<DoctorPhone>202-555-0101</DoctorPhone>
					<DoctorPhone>202-555-0122</DoctorPhone>
				</DoctorContact>
			</Doctor>
			<Doctor DoctorID="Doctor103" WorksIn="_Nephrology">
				<DoctorName>Ollie Holloway</DoctorName>
				<Speciality>Nephrologist</Speciality>
				<Relantionship RelantionshipType="Visiting"/>
				<DoctorContact>
					<DoctorAddress>50 Water Street Gulfport, MS 39503</DoctorAddress>
					<DoctorPhone>202-555-0154</DoctorPhone>
				</DoctorContact>
			</Doctor>
			<Doctor DoctorID="Doctor117" WorksIn="_Nephrology" HeadOfDept="_Nephrology">
				<DoctorName>Dennis Young</DoctorName>
				<Speciality>Nephrologist</Speciality>
				<Relantionship RelantionshipType="Permanent"/>
				<DoctorContact>
					<DoctorAddress>986 Lexington Court Tacoma, WA 98444</DoctorAddress>
					<DoctorPhone>202-555-0128</DoctorPhone>
					<DoctorPhone>202-555-0144</DoctorPhone>
				</DoctorContact>
			</Doctor>
			<Doctor DoctorID="Doctor104" WorksIn="_Microbiology">
				<DoctorName>Marlon Carpenter</DoctorName>
				<Speciality>Microbiologist</Speciality>
				<Relantionship RelantionshipType="Permanent"/>
				<DoctorContact>
					<DoctorAddress>146 Route 9 Media, PA 19063</DoctorAddress>
					<DoctorPhone>202-555-0144</DoctorPhone>
					<DoctorPhone>202-555-0199</DoctorPhone>
				</DoctorContact>
			</Doctor>
			<Doctor DoctorID="Doctor105" WorksIn="_Microbiology">
				<DoctorName>Clayton Lynch</DoctorName>
				<Speciality>Microbiologist</Speciality>
				<Relantionship RelantionshipType="Visiting"/>
				<DoctorContact>
					<DoctorAddress>769 Sycamore Street Niles, MI 49120</DoctorAddress>
					<DoctorPhone>202-555-0180</DoctorPhone>
				</DoctorContact>
			</Doctor>
			<Doctor DoctorID="Doctor118" WorksIn="_Microbiology" HeadOfDept="_Microbiology">
				<DoctorName>Barbara Scott</DoctorName>
				<Speciality>Microbiologist</Speciality>
				<Relantionship RelantionshipType="Permanent"/>
				<DoctorContact>
					<DoctorAddress>621 Ridge Avenue Elkhart, IN 46514</DoctorAddress>
					<DoctorPhone>202-555-0134</DoctorPhone>
				</DoctorContact>
			</Doctor>
			<Doctor DoctorID="Doctor106" WorksIn="_Oncology">
				<DoctorName>Joe	Powell</DoctorName>
				<Speciality>Oncologist</Speciality>
				<Relantionship RelantionshipType="Permanent"/>
				<DoctorContact>
					<DoctorAddress>230 Durham Road Allentown, PA 18102</DoctorAddress>
					<DoctorPhone>202-555-0108</DoctorPhone>
					<DoctorPhone>202-555-0158</DoctorPhone>
					<DoctorPhone>202-555-0151</DoctorPhone>
				</DoctorContact>
			</Doctor>
			<Doctor DoctorID="Doctor107" WorksIn="_Oncology">
				<DoctorName>Anne Griffin</DoctorName>
				<Speciality>Oncologist</Speciality>
				<Relantionship RelantionshipType="Trainee"/>
				<DoctorContact>
					<DoctorAddress>755 Front Street South Vincentown, NJ 08088</DoctorAddress>
					<DoctorPhone>202-555-0105</DoctorPhone>
				</DoctorContact>
			</Doctor>
			<Doctor DoctorID="Doctor119" WorksIn="_Oncology">
				<DoctorName>Frank Murphy</DoctorName>
				<Speciality>Oncologist</Speciality>
				<Relantionship RelantionshipType="Permanent"/>
				<DoctorContact>
					<DoctorAddress>15 College Avenue Great Falls, MT 59404</DoctorAddress>
					<DoctorPhone>202-555-0187</DoctorPhone>
				</DoctorContact>
			</Doctor>
			<Doctor DoctorID="Doctor120" WorksIn="_Oncology" HeadOfDept="_Oncology">
				<DoctorName>Brandon Smith</DoctorName>
				<Speciality>Oncologist</Speciality>
				<Relantionship RelantionshipType="Permanent"/>
				<DoctorContact>
					<DoctorAddress>309 Aspen Drive West Roxbury, MA 02132</DoctorAddress>
					<DoctorPhone>202-555-0111</DoctorPhone>
				</DoctorContact>
			</Doctor>
			<Doctor DoctorID="Doctor108" WorksIn="_Cardiology">
				<DoctorName>Fred Hill</DoctorName>
				<Speciality>Cardiologist</Speciality>
				<Relantionship RelantionshipType="Permanent"/>
				<DoctorContact>
					<DoctorAddress>374 Westminster Drive Florence, SC 29501</DoctorAddress>
					<DoctorPhone>202-555-0111</DoctorPhone>
					<DoctorPhone>202-555-0190</DoctorPhone>
				</DoctorContact>
			</Doctor>
			<Doctor DoctorID="Doctor109" WorksIn="_Cardiology">
				<DoctorName>Terry Thomas</DoctorName>
